[project]
name = "CalculiX"
version = "0.1.0"
description = "Add a short description here"
authors = ["looooo <sppedflyer@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
test_activation = "echo $CMAKE_PREFIX_PATH"
init = { cmd = ["git", "submodule", "update", "--init", "--recursive"]}
configure_pastix = { cmd = ["cmake", "-G", "Ninja", "-B", "build", "-S", "pastix",
                             "-D", "GIT_SUBMODULE=OFF",
                             "-D", "CMAKE_BUILD_TYPE='Release'",
                             "-D", "BUILD_SHARED_LIBS=ON",
                             "-D", "CMAKE_INSTALL_PREFIX:FILEPATH=$CONDA_PREFIX",
                             "-D", "PASTIX_ORDERING_SCOTCH:BOOL=OFF",
                             "-D", "BLAS_DIR=$CONDA_PREFIX/lib"], depends-on = ["init"]}
build_pastix = {cmd = ["ninja", "-C", "build", "install"], depends-on = ["configure_pastix"]}
configure = {cmd = ["cd", "ccx*/src/", "&&", 
                "export", "CFLAGS=$CFLAGS -Wno-error=implicit-function-declaration", "&&",
                "make", "-f", "Makefile_conda",
                "SPOOLES_INCLUDE_DIR='${CONDA_PREFIX}/include/spooles'",
                "LIB_DIR='${CONDA_PREFIX}/lib'",
                "VERSION='2.22'"], depends-on = ["build_pastix"]}
build = {cmd = ["cp", "ccx*/src/ccx_*_conda", "$CONDA_PREFIX/bin/ccx"], depends-on = ["configure"]}
test = "lldb ccx tests/test"

[dependencies]
libblas = ">=3.9.0,<4"
liblapack = ">=3.9.0,<4"
arpack = ">=3.9.1,<4"
spooles = ">=2.2.0,<3"
make = ">=4.3,<5"
gfortran = ">=13.2.0,<14"
libcblas = ">=3.9.0,<4"
liblapacke = ">=3.9.0,<4"
libhwloc = ">=2.11.1,<3"
metis = ">=5.1.0,<6"
ninja = ">=1.12.1,<2"
cmake = ">=3.30.1,<4"
pkgconfig = ">=1.5.5,<2"
python = ">=3.12.4,<4"
