[project]
name = "CalculiX"
version = "0.1.0"
description = "Add a short description here"
authors = ["looooo <sppedflyer@gmail.com>"]
channels = ["freecad/label/dev", "conda-forge"]
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]

[tasks]
test_activation = "echo $CMAKE_PREFIX_PATH"
init = { cmd = ["git", "submodule", "update", "--init", "--recursive"]}
configure = {cmd = ["cd", "ccx*/src/", "&&", 
                "export", "CFLAGS=$CFLAGS -Wno-error=implicit-function-declaration", "&&",
                "make", "-f", "Makefile_conda",
                "SPOOLES_INCLUDE_DIR='${CONDA_PREFIX}/include/spooles'",
                "LIB_DIR='${CONDA_PREFIX}/lib'",
                "VERSION='2.22'"]}
build = {cmd = ["cp", "ccx*/src/ccx_*_conda", "$CONDA_PREFIX/bin/ccx"], depends-on = ["configure"]}
test = "gdb ccx tests/test"

[dependencies]
arpack = "*"
spooles = "*"
make = "*"
fortran-compiler = "*"
pastix = "*"

[target.linux-aarch64.dependencies]
gxx = "*"
